/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by `next dev` / `next build`.
// It is checked in here so the project type-checks immediately after
// `npm install`, but Next.js will keep it up to date automatically.
